In [12]:
import os
import pickle
import numpy as np
from sklearn.ensemble import RandomForestClassifier, RandomTreesEmbedding
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
from sklearn.model_selection import train_test_split

In [13]:
faces_embeddings = np.load("faces_embeddings_done_14classes.npz")
Y = faces_embeddings['arr_1']
X = faces_embeddings["arr_0"]

In [14]:
encoder = LabelEncoder()
encoder.fit(Y)
Y = encoder.transform(Y)

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, shuffle=True, random_state=17)

In [16]:
model = RandomForestClassifier()
model.fit(X_train, Y_train)

RandomForestClassifier()

In [17]:
ypreds_test = model.predict(X_test)

In [18]:
accuracy_score(Y_test, ypreds_test)

0.9975961538461539

In [19]:
classes = ["Aarin", "Adithya", "Aditya", "Avanish", "Dev", "Dhruv Arora", "Parth Waman", "Shimpali", "Shourya", "Siddharth", "Tanuj", "Tarush", "Utkarsh", "Vaibhav"]

In [23]:
print(classification_report(Y_test, ypreds_test, target_names=classes))

              precision    recall  f1-score   support

       Aarin       0.97      1.00      0.98        64
     Adithya       1.00      1.00      1.00        53
      Aditya       1.00      1.00      1.00        58
     Avanish       1.00      1.00      1.00        64
         Dev       1.00      1.00      1.00        69
 Dhruv Arora       1.00      1.00      1.00        43
 Parth Waman       1.00      0.98      0.99        61
    Shimpali       1.00      0.98      0.99        55
     Shourya       1.00      1.00      1.00        64
   Siddharth       1.00      1.00      1.00        63
       Tanuj       1.00      1.00      1.00        59
      Tarush       1.00      1.00      1.00        61
     Utkarsh       1.00      1.00      1.00        50
     Vaibhav       1.00      1.00      1.00        68

    accuracy                           1.00       832
   macro avg       1.00      1.00      1.00       832
weighted avg       1.00      1.00      1.00       832


In [24]:
print(confusion_matrix(Y_test, ypreds_test))

[[64  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 53  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 58  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 64  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 69  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 43  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0 60  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0 54  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 64  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 63  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 61  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 50  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 68]]


In [22]:
#save the model
with open('random_forest_160x160.pkl','wb') as f:
    pickle.dump(model,f)