In [2]:
import os
import pickle
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, confusion_matrix
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
from sklearn.model_selection import train_test_split

In [3]:
faces_embeddings = np.load("faces_embeddings_done_14classes.npz")
Y = faces_embeddings['arr_1']
X = faces_embeddings["arr_0"]

In [4]:
encoder = LabelEncoder()
encoder.fit(Y)
Y = encoder.transform(Y)

In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, shuffle=True, random_state=17)

In [5]:
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

In [6]:
ypreds_test = model.predict(X_test)

In [9]:
accuracy_score(Y_test, ypreds_test)

0.9891826923076923

In [7]:
print(classification_report(Y_test, ypreds_test))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98        64
           1       0.95      1.00      0.97        53
           2       0.98      0.95      0.96        58
           3       1.00      1.00      1.00        64
           4       1.00      0.99      0.99        69
           5       1.00      1.00      1.00        43
           6       1.00      0.98      0.99        61
           7       0.96      0.95      0.95        55
           8       1.00      1.00      1.00        64
           9       0.98      1.00      0.99        63
          10       1.00      1.00      1.00        59
          11       0.98      1.00      0.99        61
          12       1.00      1.00      1.00        50
          13       1.00      1.00      1.00        68

    accuracy                           0.99       832
   macro avg       0.99      0.99      0.99       832
weighted avg       0.99      0.99      0.99       832


In [8]:
print(confusion_matrix(Y_test, ypreds_test))

[[63  0  0  0  0  0  0  1  0  0  0  0  0  0]
 [ 0 53  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  1 55  0  0  0  0  0  0  1  0  1  0  0]
 [ 0  0  0 64  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 68  0  0  1  0  0  0  0  0  0]
 [ 0  0  0  0  0 43  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0 60  0  0  0  0  0  0  0]
 [ 0  2  1  0  0  0  0 52  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 64  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 63  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 59  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 61  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 50  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 68]]


In [11]:
#save the model
with open('logistic_regression_160x160.pkl','wb') as f:
    pickle.dump(model,f)